// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtDRtjxF8CvG0KG08PJvkbc28tj_n4AV8',
    appId: '1:1001813168693:web:efcb32b45abf17beb3177c',
    messagingSenderId: '1001813168693',
    projectId: 'saveone-d2799',
    authDomain: 'saveone-d2799.firebaseapp.com',
    storageBucket: 'saveone-d2799.firebasestorage.app',
    measurementId: 'G-LGFZKCRMDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm6f40pxuOiMTFC9XlOzmBYAaM48SsvdY',
    appId: '1:1001813168693:android:7f109aa3d94ac816b3177c',
    messagingSenderId: '1001813168693',
    projectId: 'saveone-d2799',
    storageBucket: 'saveone-d2799.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBYm2_mYW_lBn_lfjI9-4wxOiJJEnxjIE',
    appId: '1:1001813168693:ios:98df0f7573095bf5b3177c',
    messagingSenderId: '1001813168693',
    projectId: 'saveone-d2799',
    storageBucket: 'saveone-d2799.firebasestorage.app',
    iosBundleId: 'com.example.saveone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBYm2_mYW_lBn_lfjI9-4wxOiJJEnxjIE',
    appId: '1:1001813168693:ios:98df0f7573095bf5b3177c',
    messagingSenderId: '1001813168693',
    projectId: 'saveone-d2799',
    storageBucket: 'saveone-d2799.firebasestorage.app',
    iosBundleId: 'com.example.saveone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtDRtjxF8CvG0KG08PJvkbc28tj_n4AV8',
    appId: '1:1001813168693:web:c0bfef5583b46122b3177c',
    messagingSenderId: '1001813168693',
    projectId: 'saveone-d2799',
    authDomain: 'saveone-d2799.firebaseapp.com',
    storageBucket: 'saveone-d2799.firebasestorage.app',
    measurementId: 'G-B627JMPXLS',
  );
}
